name: quiz_section
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/sunset.png
    - assets/Fonts/

  fonts:
    - family: Silkscreen
      fonts:
        - asset: assets/Fonts/Silkscreen-Regular.ttf
        - asset: assets/Fonts/Silkscreen-Bold.ttf
          weight: 700
    - family: Montserrat
      fonts:
      - asset: assets/Fonts/Montserrat-Black.ttf
        weight: 900
      - asset: assets/Fonts/Montserrat-Bold.ttf
        weight: 700
      - asset: assets/Fonts/Montserrat-Medium.ttf
        weight: 500
      - asset: assets/Fonts/Montserrat-SemiBold.ttf
        weight: 600
      - asset: assets/Fonts/Montserrat-Regular.ttf